# Generated by Django 6.0.2 on 2026-02-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Serviço de interesse')),
                ('message', models.TextField(verbose_name='Mensagem / Detalhes do projeto')),
                ('budget_estimated', models.CharField(blank=True, max_length=100, null=True, verbose_name='Orçamento estimado (opcional)')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contactado'), ('in_progress', 'Em andamento'), ('closed', 'Fechado')], default='new', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Solicitação de Orçamento',
                'verbose_name_plural': 'Solicitações de Orçamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
